[package]
name = "processor"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
postcard = { version = "1", features = ["alloc"] }

scraper = "0.19"
url = "2.5"
clap = { version = "4.4", features = ["derive"] }
chrono = "0.4"
regex = "1.10"
whatlang = "0.16"
arrow = "53"
parquet = { version = "53", features = ["arrow", "zstd"] }
tantivy = "0.26"
